name: calculator2
description: A new Flutter project from Muhamad Bagus Prasetyo.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  material_design_icons_flutter: ^7.0.7296
  math_expressions: ^2.4.0
  path_provider: ^2.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  integrations:
    flutter_svg: true
  line_length: 80
  output: lib/helpers

flutter:
  assets:
    - assets/images/
  uses-material-design: true
