name: calculator2
description: A new Flutter project from Muhamad Bagus Prasetyo.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  material_design_icons_flutter: ^7.0.7296
  math_expressions: ^2.4.0
  path_provider: ^2.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  integrations:
    flutter_svg: true
  line_length: 80
  output: lib/helpers

flutter:
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo/Archivo-Black.ttf
          weight: 900
        - asset: assets/fonts/Archivo/Archivo-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Archivo/Archivo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Archivo/Archivo-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Archivo/Archivo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Archivo/Archivo-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Archivo/Archivo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Archivo/Archivo-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Archivo/Archivo-Italic.ttf
          style: italic
        - asset: assets/fonts/Archivo/Archivo-Light.ttf
          weight: 300
        - asset: assets/fonts/Archivo/Archivo-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Archivo/Archivo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Archivo/Archivo-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Archivo/Archivo-Regular.ttf
        - asset: assets/fonts/Archivo/Archivo-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Archivo/Archivo-SemiboldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Archivo/Archivo-Thin.ttf
          weight: 100
        - asset: assets/fonts/Archivo/Archivo-ThinItalic.ttf
          style: italic
          weight: 100
  uses-material-design: true
